@Ctoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDRiNmRiNzI1ZjFmNDMzNjNiMzY1MiIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc4MjkwMzA5NywiZXhwIjoxNzgyOTg5NDk3fQ.eKDycb8DCvSyNpb-D32SnZHj42H7dIMNJ7PYKCPjEuo

@Otoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDM5YmI5NGFkMWU0YjM3ZDM3ZDZjOCIsInJvbGUiOiJzdG9yZV9vd25lciIsImlhdCI6MTc4MjgxNjEwOCwiZXhwIjoxNzgyOTAyNTA4fQ.4Qk8ONy93-uJ9NqIRk3_wtzvJ66qAL461pTFaugKFbg

@Atoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDM5YmQzNGFkMWU0YjM3ZDM3ZDZjOSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4MjgxNTg2NCwiZXhwIjoxNzgyOTAyMjY0fQ._Xt39r7vBsuLZkPiibYeL2YvAXHzP2KoS62HlQp1LVo
### Register Customer

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstName": "Store",
    "lastName": "Owner",
    "email": "store-owner@gmail.com",
    "password": "123456",
}

### Login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "jiveneo@gmail.com",
    "password": "12345678"
}

### Invalid Login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "kevin@gmail.com",
    "password": "wrongpassword"
}

### Profile without Token

GET http://localhost:3000/api/auth/profile

### Profile with Token

GET http://localhost:3000/api/auth/profile
Authorization: Bearer {{Ctoken}}

### Testing Customer Account

GET http://localhost:3000/api/auth/customer
Authorization: Bearer {{Ctoken}}


### Testing Store Owner Account

GET http://localhost:3000/api/auth/store-owner
Authorization: Bearer {{Otoken}}


### Testing Admin Account

GET http://localhost:3000/api/auth/admin
Authorization: Bearer {{Atoken}}

### Testing Add to Cart

POST http://localhost:3000/api/cart
Authorization: Bearer {{Ctoken}}
Content-Type: application/json

{
    "productId": "6a435fcd4ad1e4b37d37d695",
    "quantity": 1
}

### Testing Get Cart

GET http://localhost:3000/api/cart
Authorization: Bearer {{Ctoken}}

### Testing Remove from Cart

DELETE http://localhost:3000/api/cart/6a435fcd4ad1e4b37d37d69b
Authorization: Bearer {{Ctoken}}