@Ctoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDVjNzM4ZDFlM2FhNGNhNzg4NTVmYyIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc4MzE3NDMxNCwiZXhwIjoxNzgzMjYwNzE0fQ.7v0adflaqqVYSVHxVrrdEkBZ_-knHdXC9yCaCGtOnDM

@Otoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDVjNzM4ZDFlM2FhNGNhNzg4NTVmYyIsInJvbGUiOiJzdG9yZS1vd25lciIsImlhdCI6MTc4MzI0NDIzMiwiZXhwIjoxNzgzMzMwNjMyfQ.Ta562QPtw25DgfnZill1JDM-mVy70InvK69Zx0WB83Q

@Atoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDM4OTkwNTlhOTZkZGIyMzMzYTM5NSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4MzE3NDA1NSwiZXhwIjoxNzgzMjYwNDU1fQ.22ZJvkrhPFVQkPXDb4a4Mzb9kYdt85h-p3QNJgJcYpQ
### Register Customer

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstName": "Store",
    "lastName": "Owner",
    "email": "store-owner@gmail.com",
    "password": "123456",
}

### Login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "jeremysandres@gmail.com",
    "password": "12345678"
}

### Invalid Login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "kevin@gmail.com",
    "password": "wrongpassword"
}

### Profile without Token

GET http://localhost:3000/api/auth/profile

### Profile with Token

GET http://localhost:3000/api/auth/profile
Authorization: Bearer {{Ctoken}}

### Testing Customer Account

GET http://localhost:3000/api/auth/customer
Authorization: Bearer {{Ctoken}}


### Testing Store Owner Account

GET http://localhost:3000/api/auth/store-owner
Authorization: Bearer {{Otoken}}


### Testing Admin Account

GET http://localhost:3000/api/auth/admin
Authorization: Bearer {{Atoken}}

### Testing Add to Cart

POST http://localhost:3000/api/cart
Authorization: Bearer {{Ctoken}}
Content-Type: application/json

{
    "productId": "6a435fcd4ad1e4b37d37d695",
    "quantity": 1
}

### Testing Get Cart

GET http://localhost:3000/api/cart
Authorization: Bearer {{Ctoken}}

### Testing Remove from Cart

DELETE http://localhost:3000/api/cart/6a435fcd4ad1e4b37d37d69b
Authorization: Bearer {{Ctoken}}

### Testing Send for an Application (POST)

POST http://localhost:3000/api/store-applications
Authorization: Bearer {{Ctoken}}
Content-Type: application/json

{
  "storeName": "Kevin's Coffee Shop",
  "description": "Coffee and pastries",
  "address": "Manila",
  "phone": "09123456789"
}

### Testing Viewing of Applications (ADMIN)

GET http://localhost:3000/api/store-applications
Authorization: Bearer {{Atoken}}

### Testing Approval of an Application

PUT http://localhost:3000/api/store-applications/6a4912b414a1e162d39e1788/approve
Authorization: Bearer {{Atoken}}

### Testing Rejecting of an Application

PUT http://localhost:3000/api/store-applications/6a4914be14a1e162d39e1789/reject
Authorization: Bearer {{Atoken}}

### Testing Getting All User

GET http://localhost:3000/api/users
Authorization: Bearer {{Atoken}}

### Testing Dashboard Analytics 

GET http://localhost:3000/api/admin/dashboard
Authorization: Bearer {{Atoken}}

### Testing Creating Store

POST http://localhost:3000/api/stores
Authorization: Bearer {{Otoken}}
Content-Type: application/json

{
    "storeName":"Kevin's Coffee",
    "description":"The best coffee in town",
    "address":"Manila, Philippines",
    "latitude":14.5995,
    "longitude":120.9842,
    "phone":"09123456789"
}

### Testing Getting Store

GET http://localhost:3000/api/stores/me
Authorization: Bearer {{Otoken}}

### Testing Posting Product

POST http://localhost:3000/api/products
Authorization: Bearer {{Otoken}}
Content-Type: application/json

{
  "name": "Espresso",
  "description": "Fresh brewed coffee",
  "price": 120,
  "stock": 30,
  "category": "Coffee",
  "imageUrl": ""
}

### Testing Image Upload

POST http://localhost:3000/api/products/upload
Authorization: Bearer {{Otoken}}


